const FOOD_DATA = [
  {
    //"index":0,
    "name":"Sushi",
    "brand":"すし",
    "price":2.99,
    "image":"Sushi.png",
    "time_to_cook":65,
    "ingredient":[
      {"name":"Calrose rice (sushi rice)","unit": "1/2", "unitname":"cup", "image":"Rice.png"},
      {"name":"Water","unit": "3/4", "unitname":"cup", "image":"Water.png"},
      {"name":"Salt","unit": "1", "unitname":"tsp", "image":"Salt.png"},
      {"name":"Rice vinegar","unit": "3", "unitname":"tbsp", "image":"RiceVinegar.png"},
      {"name":"Sugar","unit": "1", "unitname":"tbsp", "image":"Sugar.png"},
      {"name":"Skinless salmon steak","unit": "450", "unitname":"g", "image":"Salmon.png"},
      {"name":"Wasabi","unit": "1", "unitname":"tsp", "image":"Wasabi.png"},
      {"name":"Soy sauce","unit": "1", "unitname":"tsp", "image":"SoySauce.png"},
      {"name":"Ginger","unit": "1", "unitname":"tsp", "image":"Ginger.png"},
    ],
    "steps":[
      "1. In a bowl, cover the rice with cold water. Rinse the rice until the water becomes cloudy. Drain and repeat 4 to 5 times or until the water runs clear. Leave the rice in a strainer until thoroughly drained.",
      "2. In a saucepan over high heat, bring the rice, water and salt to a boil. Cover and cook over low heat for 15 minutes or until the liquid is completely absorbed. Remove from the heat and let rest, covered, for 10 minutes.",
      "3. Meanwhile, in a small saucepan over medium-low heat, gently warm the vinegar and sugar until the sugar has dissolved.",
      "4. Spread the cooked rice onto a baking sheet and pour the vinegar mixture overtop. Gently combine to coat and separate the grains of rice. Spread out the rice again and cover with plastic wrap. Let cool slightly.",
      "5. With a sharp knife, trim and discard the discoloured sections of the salmon. While holding the knife at 30°, finely slice the fish against the grain to obtain slices 4 inches (10 cm) long (see note). Set aside on a cold plate or refrigerate while shaping the rice balls.",
      "6. With slightly moistened hands, shape the rice into 2 1/2-inch (6 cm) oblong balls using 2 tbsp of rice for each. Spread a small amount of wasabi onto each rice ball, to taste, and cover with a salmon slice.",
      "7. Serve with the soy sauce and pickled ginger.",
    ]
  },
  {
    //"index":1,
    "name":"Ramen",
    "brand":"ラーメン",
    "price":2.99,
    "image":"Ramen 2.png",
    "time_to_cook":40,
    "ingredient":[
      {"name":"Chicken stock","unit": 700, "unitname":"ml", "image":"Soup.png"},
      {"name":"Garlic cloves (Halved)","unit": 3, "unitname":"ea", "image":"Garlic.png"},
      {"name":"Soy sauce (+Extra to season)","unit": 4, "unitname":"tbsp", "image":"SoySouce 2.png"},
      {"name":"Worcestershire sauce","unit": 1, "unitname":"tsp", "image":"WorcestershireSauce.png"},
      {"name":"Thumb-sized piece of Ginger, sliced","unit": 1, "unitname":"ea", "image":"GingerSlice.png"},
      {"name":"Chinese five spice","unit": "1/2", "unitname":"tsp", "image":"SpicePowder.png"},
      {"name":"Pinch of chili powder","unit": 1, "unitname":"ea", "image":"ChiliiPowder.png"},
      {"name":"White sugar (optional)","unit": 1, "unitname":"tsp", "image":"Sugar.png"},
      {"name":"Ramen noodles","unit": 375, "unitname":"g", "image":"RamenNoodle.png"},
      {"name":"Sliced cooked pork or Chicken breast","unit": 400, "unitname":"g", "image":"Pork.png"},
      {"name":"Sesame oil","unit": 2, "unitname":"tsp", "image":"SesameOil.png"},
    ],
    "steps":[
      "1. Mix 700ml chicken stock, 3 halved garlic cloves, 4 tbsp soy sauce, 1 tsp Worcestershire sauce, a sliced thumb-sized piece of ginger, ½ tsp Chinese five spice, pinch of chilli powder and 300ml water in a stockpot or large saucepan, bring to the boil, then reduce the heat and simmer for 5 mins.",
      "2. Taste the stock – add 1 tsp white sugar or a little more soy sauce to make it sweeter or saltier to your liking.",
      "3. Cook 375g ramen noodles following the pack instructions, then drain and set aside.",
      "4. Slice 400g cooked pork or chicken, fry in 2 tsp sesame oil until just starting to brown, then set aside.",
      "5. Divide the noodles between four bowls. Top each with a quarter of the meat, 25g spinach, 1 tbsp sweetcorn and two boiled egg halves each.",
      "6. Strain the stock into a clean pan, then bring to the boil once again.",
      "7. Divide the stock between the bowls, then sprinkle over 1 shredded nori sheet, sliced spring onions or shallots and a sprinkle of sesame seeds. Allow the spinach to wilt slightly before serving.\n\n",
    ]
  },
  {
    //"index":2,
    "name":"Japanese Curry",
    "brand":"日本のカレー",
    "price":2.99,
    "image":"Japanese Curry.png",
    "time_to_cook":30,
    "ingredient":[
      {"name":"Uncooked rice","unit": "1 2/3", "unitname":"cups", "image":"UncookRice.png"},
      {"name":"Curry Roux","unit": "1/2 (*2)", "unitname":"large packet", "image":"CurryBox.png"},
      {"name":"Your preferred protein","unit": "9 (*3)", "unitname":"oz", "image":"Meat.png"},
      {"name":"Brown onion","unit": 1, "unitname":"ea", "image":"Onion.png"},
      {"name":"Large potato","unit": 4, "unitname":"ea", "image":"Potato.png"},
      {"name":"Carrot","unit": 5, "unitname":"ea", "image":"Carrot.png"},
      {"name":"Olive oil","unit": 1, "unitname":"tbsp", "image":"OliveOil.png"},
      {"name":"Garlic","unit": 2, "unitname":"cloves", "image":"Garlic.png"},
      {"name":"Grated apple","unit": 1/4, "unitname":"cup", "image":"Apple.png"},
      {"name":"Honey","unit": 1, "unitname":"tbsp", "image":"Honey.png"},
      {"name":"Water","unit": 1000, "unitname":"ml", "image":"Water.png"},
      {"name":"Fukushinduke and/or Rakkyo", "unit":"Up", "unitname":"to you", "image":"Fukushinduke and Rakkyo.png"},
      {"name":"Worcestershire sauce", "unit":"Up" ,"unitname":"to you", "image":"WorcestershireSauce.png"},
    ],
    "steps":[
      "1. Start to cook rice.",
      "2. Cut the meat into bite size pieces and set aside",
      "3. Peel and cut the potatoes, carrot, and onion into large bite size pieces and set aside.",
      "4. Peel and slice the garlic.",
      "5. Heat olive oil in a pot over medium heat and add garlic.",
      "6. When the garlic is fragrant, add the onion to cook.",
      "7. Add the chicken to cook and when they change into whitish colour, add potato, carrot, and onion and stir with a wooden spatula.",
      "8. When the oil has coated evenly on all the ingredients and the outer-edge of the potatoes have become transparent, add the water, honey, and grated apple.",
      "9. Bring it to boil and then turn the heat down to low to simmer until the potatoes become soft. and all the other ingredients are cooked. (Takes about 15 minutes)",
      "10. Turn the heat off, break the curry sauce blocks apart and add to the pot.",
      "11. Make each piece of curry roux dissolve into the cooking water in ladle with a pair of chopsticks",
      "12. Turn the heat back on low and bring to simmer to thicken the sauce.",
      "13. Serve cooked plain rice in a shallow bowl and pour the curry over the rice.",
      "14. Garnish with Fukushinduke and Rakkyo if you like. *Optional",
    ]
  },
  {
    //"index":3,
    "name":"Shrimp Tempura",
    "brand":"エビの天ぷら",
    "price":2.99,
    "image":"Shrimp Tempura.png",
    "time_to_cook":45,
    "ingredient":[
      {"name":"Prawn","unit": 1, "unitname":"cup", "image":"Shrimp.png"},
      {"name":"Potato starch or Cornstarch", "unit":"-", "unitname":"-", "image":"Potato.png"},
      {"name":"Neutral-flavored oil","unit": 3, "unitname":"cup", "image":"OliveOil.png"},
      {"name":"large egg","unit": 1, "unitname":"-", "image":"Egg.png"},
      {"name":"Iced water","unit": "3/4", "unitname":"cup", "image":"IceWater.png"},
      {"name":"All-purpose flour","unit": 1, "unitname":"cup", "image":"Flour.png"},
      {"name":"Dashi","unit": "3/4", "unitname":"cup", "image":"Dashi.png"},
      {"name":"Soy sauce","unit": 3, "unitname":"tbsp", "image":"SoySouce 2.png"},
      {"name":"Mirin","unit": 2, "unitname":"tbsp", "image":"Mirin.png"},
      {"name":"Sugar","unit": 2, "unitname":"tsp", "image":"Sugar.png"},
      {"name":"Daikon radish","unit": 2, "unitname":"inch", "image":"Daikon Radish.png"},
    ],
    "steps":[
      "1. Gather tempura sauce ingredients.",
      "2. Combine dashi, soy sauce, mirin, and sugar in a small saucepan and bring it to a boil. Then lower the heat and let it simmer until sugar is completely dissolved. Remove from heat and set aside.",
      "3. To prepare shrimp",
      "4. In a wok or a medium-size pot, heat 1 ½ (3 cm) of the oil to 340-350ºF (170-180ºC) and maintain the oil temperature at all times. You can check the temperature with chopsticks or with a thermometer. When you see small bubbles around chopsticks, it’s ready for deep frying.",
      "5. Gather tempura batter ingredients.",
      "6. Sift the flour into a large bowl.",
      "7. Add the egg into very cold water in the measuring cup.",
      "8. Whisk the egg mixture vigorously and discard the foam on the surface.",
      "9. Slowly pour the egg mixture into the flour. Mix the batter but do not over mix; it's okay to leave some lumps in the batter. Keep the batter cold all the time. Make batter right before deep frying to avoid activation of wheat gluten.",
      "10. Dust potato starch (or cornstarch) over the shrimp. This will help the shrimp adhere to the tempura batter.",
      "11. Coat the shrimp in the batter.",
      "12. Deep fry the shrimp until golden brown, about 2 minutes. Do not crowd the wok (pot) because the oil temperature will drop quickly. Don't overcook the shrimp; otherwise, the texture will be tough and dry. Transfer the Shrimp Tempura to a wire rack or a plate lined with a paper towel to drain excess oil. Between batches, skim the crumbs in the oil, which will burn and turn the oil darker if left in the wok (pot).",
      "13. Grate the daikon and squeeze the liquid out.",
      "14. Serve shrimp tempura with warm tempura dipping sauce and grated daikon on the side. Put some grated daikon in the dipping sauce and dip the tempura in the sauce to enjoy.",
    ]
  },
  {
    //"index":4,
    "name":"Yakisoba",
    "brand":"焼きそば",
    "price":2.99,
    "image":"Yakisoba 2.png",
    "time_to_cook":40,
    "ingredient":[
      {"name":"Soy sauce", "unit":"Up", "unitname":"to you", "image":"SoySouce 2.png"},
      {"name":"Worcestershire sauce", "unit":"2", "unitname":"tbsp", "image":"WorcestershireSauce.png"},
      {"name":"Ketchup", "unit":"1", "unitname":"tbsp", "image":"Tomato.png"},
      {"name":"Brown sugar", "unit":"Up", "unitname":"to you", "image":"BrownSugar.png"},
      {"name":"Oyster sauce", "unit":"1", "unitname":"tbsp", "image":"OysterSauce.png"},
      {"name":"Sesame oil", "unit":"1", "unitname":"tbsp", "image":"SesameOil.png"},
      {"name":"Chicken breasts", "unit":"200", "unitname":"g", "image":"Chicken.png"},
      {"name":"Yakisoba noodles", "unit":"230", "unitname":"g", "image":"YakisobaNoodle.png"},
      {"name":"Fresh veggies", "unit":"Up", "unitname":"to you", "image":"Fresh veggies.png"},
      {"name":"Garlic paste and ginger paste", "unit":"1/2", "unitname":"tbsp per piece", "image":"Garlic and Ginger.png"},
      {"name":"Vegetable oil", "unit":"1", "unitname":"tbsp", "image":"VegetableOil.png"},
    ],
    "steps":[
      "1. Bring a large pot of of water to a boil.",
      "2. Whisk together soy sauce, Worcestershire sauce, ketchup, brown sugar, oyster sauce and sesame oil.",
      "3. Boil noodles and drain.",
      "4. Cook chicken in oil in skillet. Transfer.",
      "5. Saute green onions, ginger paste and garlic and in oil.",
      "6. Add in bell pepper and mushrooms and saute. Add in cabbage and carrots and green onion greens and saute.",
      "7. Add drained noodles along with cooked chicken, toss with sauce.\n\n",
    ]
  },
  {
    //"index":5,
    "name":"Matcha Green Tea",
    "brand":"抹茶",
    "price":2.99,
    "image":"Matcha.png",
    "time_to_cook":20,
    "ingredient":[
      {"name":"Matcha (green tea powder)", "unit":"1", "unitname":"tsp", "image":"Matcha Powder.png"},
      {"name":"Boiling water", "unit":"4", "unitname":"tbsp", "image":"Boiling water.png"},
      {"name":"Chawan (Tea Bowl) 茶碗", "unit":"-", "unitname":"-", "image":"Chawan.png"},
      {"name":"Chasen (Tea Whisk) 茶筌", "unit":"-", "unitname":"-", "image":"Chasen.png"},
      {"name":"Chashaku 茶杓", "unit":"-", "unitname":"-", "image":"Chashaku.png"},
    ],
    "steps":[
      "1. Prepare matcha and tea set.",
      "2. Pour boiling water into the bowl.",
      "3. Gently whisk the tip of the Chasen in the hot water. This warms up the bowl and soften the bamboo tines, making the chasen flexible and springy for effective whisking action.",
      "4. For Usucha, scoop 1 tsp (or 1 ½ heaping tea scoops) matcha in to a fine mesh strainer over a tea bowl. For Koicha, scoop 2 tsp (or 3 heaping tea scoops) matcha into a fine-mesh strainer over a tea bowl. If you use a tea scoop or chashaku, the scoop should be rounded, reaching just the point where the chashaku starts to bend.",
      "5. Sift your matcha into your dry empty bowl. This will ensure there are no clumps and your tea will be smooth.",
      "6. Pour boiling water into a teacup and let it cools down for a minute (the temperature should be around 185ºF (85ºC).",
      "7. Gently add very small amount of hot water into the bowl with matcha.",
      "8. Take the whisk in one hand and hold the rim of the tea bowl with your other hand. Combine the matcha and hot water till it blends well.",
      "9. Gently pour hot water into the bowl, about 70 ml (⅓ full) for Usucha, and 40 ml for Koicha.",
      "10. Gently add very small amount of hot water into the bowl with matcha.",
      "11. Whisk the matcha and hot water briskly in a quick, back-and-forth stroking “W”(or “M”) motion using your wrist (not arm). When the tea has small bubbles, start whisking the surface of the tea, and continue until matcha has a thick froth with many tine bubbles on the surface.",
      "12. At the end, draw one circle and pick up the whisk in the center of the matcha tea. This will create a slightly higher fluffy foam at the center.\n\n",
    ]
  }
];